version: "3"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./wordpress/:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  nginx:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/config
      - ./nginx/nginx.conf:/config/nginx/site-confs/default
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
    container_name: nginx
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=mauro.quicknode.com
      # - SUBDOMAINS=www,
      - EMAIL=maurodelazeri@gmail.com
      - VALIDATION=http
      - STAGING=false

  mysql:
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/configs/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    image: mysql:latest
    restart: always
    env_file:
      - .env

volumes:
  wordpress-files:
    external: true
  wordpress-db:
    external: true
  letsencrypt-config:
    external: true
